[features]
seeds = false
skip-lint = false
[programs.devnet]
card = "ACYSdixSJLAewjEtKG17p4FsHVoEj1ptpB1UNv7vh4EJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/francisyang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
